
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmployeeEducationInfo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    public Employee()
    {

        this.IsDel = false;

        this.EducationInfo = new HashSet<EducationInfo>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public Nullable<int> Age { get; set; }

    public Nullable<int> Seniority { get; set; }

    public bool IsDel { get; set; }



    public virtual ICollection<EducationInfo> EducationInfo { get; set; }

}

}
