

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmployeeEducationInfo.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EmployeeEducationInfoContainer : DbContext
{
    public EmployeeEducationInfoContainer()
        : base("name=EmployeeEducationInfoContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Employee> EmployeeSet { get; set; }

    public DbSet<EducationInfo> EducationInfoSet { get; set; }

    public DbSet<Admin> AdminSet { get; set; }

}

}

